# application-dev.yml
spring:
  datasource:
    url: ${DEV_DATABASE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      pool-name: HikariCP-Dev
    datasource:
      hikari:
        connectionInitSql: "SET NAMES utf8mb4"
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: https://umctomorrow.shop/login/oauth2/code/naver

          google:
            redirect-uri: https://umctomorrow.shop/login/oauth2/code/google

          kakao:
            redirect-uri: https://umctomorrow.shop/login/oauth2/code/kakao
      
  data:
    redis:
      host: 127.0.0.1
      port: 6379

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true
  logging:
    level:
      com.umc.tomorrow: INFO
      com.umc.tomorrow.auth: INFO
      org.springframework.security: WARN
      org.springframework.security.oauth2: WARN
      org.hibernate.SQL: INFO
      org.hibernate.type.descriptor.sql.BasicBinder: WARN
    pattern:
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file:
      name: logs/tomorrow-app.log
      max-size: 10MB
      max-history: 30
# 로그 파일은 logs/tomorrow-app.log로 저장되며, 10MB 단위로 최대 30개까지 보관됨.
