spring:
  datasource:
    url: ${DEV_DATABASE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      pool-name: HikariCP-Dev
      # 초기 문자셋
      connectionInitSql: "SET NAMES utf8mb4"

  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: https://umctomorrow.shop/login/oauth2/code/naver
          google:
            redirect-uri: https://umctomorrow.shop/login/oauth2/code/google
          kakao:
            redirect-uri: https://umctomorrow.shop/login/oauth2/code/kakao

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true

# ⬇⬇⬇ 중요: logging은 spring 바깥(최상위)으로 이동 ⬇⬇⬇
logging:
  level:
    # 우리 서비스/레포 디버그
    com.umc.tomorrow.domain.job.service.query.JobQueryServiceImpl: DEBUG
    com.umc.tomorrow.domain.job.repository.JobRecommendationJpaRepository: DEBUG

    # 하이버네이트 SQL과 바인딩 값
    org.hibernate.SQL: DEBUG
    # Hibernate 6.x 파라미터 바인딩 로그
    org.hibernate.orm.jdbc.bind: TRACE
    # (만약 5.x면 아래 것도 사용)
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

    # 나머지 기본 레벨 (원래 네 설정을 유지)
    com.umc.tomorrow: INFO
    com.umc.tomorrow.auth: INFO
    org.springframework.security: WARN
    org.springframework.security.oauth2: WARN

  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

  # 로그 롤링 (Spring Boot 3 권장 키)
  file:
    name: logs/tomorrow-app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
