# application-local.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tomorrow_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      pool-name: HikariCP-Local

  # JPA 설정 (로컬 개발용)
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true


# JWT 시크릿 키 설정 추가
jwt:
  secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

# 전반
com.umc.tomorrow: DEBUG

# 인증
com.umc.tomorrow.auth: TRACE
com.umc.tomorrow.auth.service: DEBUG

# Spring Security / OAuth
org.springframework.security: DEBUG
org.springframework.security.oauth2: TRACE

# JPA / SQL
org.hibernate.SQL: DEBUG
org.hibernate.type.descriptor.sql.BasicBinder: TRACE
